#define ONLINE

using System;
using System.IO;
using System.Windows.Forms;
using System.Threading;
using DevComponents.DotNetBar;
using Modex360.Server;
using System.Reflection;
using Modex360.Functions;
using System.Diagnostics;
using System.Text;

namespace Modex360
{
    internal static class Program
    {
        private static Thread loadingLogo;
        private const string dllName = "dwmapi.dll";
        internal static bool doneLoading = false, shuttingDown = false;
        internal static string updateURL, updateVersion, updateBatch;

        [System.Runtime.InteropServices.DllImport(dllName, PreserveSig = false)]
        private static extern bool DwmIsCompositionEnabled();

        [STAThread] // Main entry point.
        private static void Main(string[] args)
        {
            var curPath = Path.GetDirectoryName(Process.GetCurrentProcess().Modules[0].FileName);
            var lzoPath = curPath + "\\lzo.dll";
            var class3Path = curPath + "\\class3.dll";

            if (!File.Exists(lzoPath))
                return;
            if (!File.Exists(class3Path))
                return;

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(MessageBoxEx.EnableGlass = false);
            StyleManager.Style = eStyle.Office2010Silver;

            Config.initSettings();
            loadingLogo = new Thread((ThreadStart)delegate
                {
                    new Forms.Splash(Properties.Resources.LoadingLogo);
                });
            loadingLogo.Start();
            if (args.Length > 0)
                Forms.Main.fixFiles(args);
            else
            {
                Application.Run(new Forms.Main());
                ProfileManager.SaveCache();
            }
        }

        internal static readonly bool isWindows7 =
            Environment.OSVersion.Platform == PlatformID.Win32NT
            && Environment.OSVersion.Version.Major >= 6
            && Environment.OSVersion.Version.Minor >= 1;

        internal static bool glassEnabled
        {
            get
            {
                if (Environment.OSVersion.Platform == PlatformID.Win32NT && Environment.OSVersion.Version.Major > 5)
                    return DwmIsCompositionEnabled();
                return false;
            }
        }

        // Call this function to abort the loading logo thread.
        internal static void killLoadingLogo()
        {
            if (loadingLogo.IsAlive)
                Forms.Splash.Alive = false;
        }

        // Runs a new instance of the Main form if a hash generated by the server checks out valid.
        internal static bool doXMLInit(System.Xml.XPath.XPathNavigator nav)
        {
            if ((Encoding.ASCII.GetString(Config.clientAES) + Security.getMachineIdent()).Hash(HashType.SHA1) == nav.Value)
            {
                nav.MoveToFirstAttribute();
                nav.MoveToParent();
                Application.Run(new Forms.Main());
                return true;
            }
            return false;
        }
    }
}

namespace Runtime
{
    public static class Includes
    {
        public static string RuntimeDLL = "Modex360.dll";
    }
}